### ISSUE TITLE
SymEngine changing species names to mathematical constants

### ISSUE THREAD

**Issue by isaacsas** [SciML/DiffEqBiological.jl#129]
`SymEngine.Basic(:(K4*E))` resolves as `exp(1)*K4`. This is going to be a problem for networks using variable names like `E`.

**Comment by isaacsas** [comment]
For example, the example [here](https://discourse.julialang.org/t/solving-highly-stiff-chemical-kinetics-ivp-using-diffeqbiological/25247/4) no longer loads correctly in the latest release.

**Comment by ChrisRackauckas** [comment]
We really need to get rid of SymEngine. I'll see if I find the time. I feel like if I just get it done one time and we are at ModelingToolkit, it'll be better for everyone.

**Comment by isaacsas** [comment]
Definitely! It is only used in a few places by my count. Basically for forming a simple expression, differentiating it, and pulling out the resulting expression.

**Comment by isaacsas** [comment]
Three fixes are needed here (each replacing user specified species or parameter names with internal names that do not overlap with SymEngine constants)

- [X] Use internal species names when calculating the Jacobian. Fixed by #131.
- [ ] Use internal parameter names when calculating the Jacobian. 
- [ ] Use internal species names when calculating the parameter Jacobian. 
- [ ] Use internal parameter names when calculating the parameter Jacobian.

**Comment by ChrisRackauckas** [comment]
Bye SymEngine
