### ISSUE TITLE
Relax type requirements of the equilibration functionality.

### ISSUE THREAD

**Issue by korsbo** [SciML/DiffEqBiological.jl#134]
Some functions and types used for equilibration or bifurcation analysis have more restrictive type signatures than needed. 

For example
```julia
function stability(solutions::Vector{Vector{Float64}}, rn::DiffEqBase.AbstractReactionNetwork, p::Vector{Float64}, t=0.::Float64)

....

struct BifurcationPath
    p_vals::Vector{Float64}
    vals::Vector{Vector{Float64}}
    jac_eigenvals::Vector{Vector{ComplexF64}}
    stability_types::Vector{Int8}
    length::Int64
end
```

I think that it would make sense to relax/remove these demands. It is not currently causing me any issues, but when we do not truly need a `Float64` I do not think that we should not demand one.

**Comment by TorkelE** [comment]
Should be sensible. I was uncertain when and were and to what extent types should be specified. Ending with the strictest possible definition. Relaxing them should be no problem.

**Comment by TorkelE** [comment]
Concerns a now deprecated feature.
