### ISSUE TITLE
Predefine reaction network structure outside macro

### ISSUE THREAD

**Issue by isaacsas** [SciML/DiffEqBiological.jl#158]
Is there any reason to not switch our code which generates a structure with the user's given typename within the macro to instead have a concrete `mutable struct` type that is simply instantiated in the macro? One drawback is that the user would no longer be able to give a type name for the generated `struct`, but an advantage of this approach is that users would be able to generate networks within functions. i.e. something like:
```julia
function getrn()
    @reaction_network begin
        c1, s + i --> 2i
        c2, i --> r
    end c1 c2
end
```
currently gives an error message 
```
ERROR: syntax: "struct" expression not at top level
```
but would work with a predefined structure type. 

@TorkelE @ChrisRackauckas any thoughts?

**Comment by TorkelE** [comment]
So personally I do not have much input, since I don't use the possibility of designating specific type names for a specific instance of a network (nor generated network in functions). However, I know that @korsbo utilises this to a good extent, and he has some applications were the possibility to designate specific typenames are very useful. He probably can describe it better than me.

**Comment by korsbo** [comment]
I often use several different models for a given project (typically comparing them). I then rely on their types for overloads to model specific methods `simulate`, `equlibrate`, `perturb`, etc.. I also tend to save parameter vectors in a struct which contains a reference to the type of the model for which they are intended. This allows for some convenient storage of parameters in a big heap which is amenable to filtering. In my case this looks something like.

```julia
model_params = @filter(param_sets, model isa MyModelType)
``` 
which essentially does an array comprehension with some filtering.

So, currently, I rely on 
- the models having different types.
- the ability to reference them in structs without making copies.
- the ability to save and load such structs with `JLD2`. 

With your proposed changes, it may still be possible to achieve this by wrapping model objects in new types but I think that it might get clunky. I'm not dogmatic about this, but at first glance, it is not clear to me that the proposed changes would be net positive.

**Comment by isaacsas** [comment]
Currently it seems that the macro can not be used to generate networks within functions, see my example above. This seems very limiting, especially if we want to allow people to create networks in anything beyond scripts. Or if we want to write functions that combine networks, or calculate the intersection of networks. Is there another approach that makes more sense? I'm far from a macro expert, so there may be an easy way I'm not aware of... I guess we can require the user to pass in a predefined network we fill in, but still this limitation seems unnecessary to me.

**Comment by TorkelE** [comment]
One, admittedly a bit ugly, solution might be to create two different macros, essentially doing the same thing.

However, one could have the advantage to be used within a function, the other to allow for custom types.

**Comment by ChrisRackauckas** [comment]
This is no longer a thing.
