### ISSUE TITLE
`stability` does not return correct answer.

### ISSUE THREAD

**Issue by danielchen26** [SciML/DiffEqBiological.jl#163]
`# ================ CRN ======================
using DiffEqBiological, LinearAlgebra
crn = @reaction_network begin
    (a1, k2*a1),              l1 + l2 ↔ cp
    (d, d),                   cp + cp ↔ mm
    (nt, k1*nt),        mm + a1 ↔ a2
    (nt, k1*nt),        mm + a3 ↔ a4
    (a7, k4*a7),              l4 + a1 ↔ a3
    (a7, k4*a7),              l4 + a2 ↔ a4
    (nt, k1*nt),        mm + s1 ↔ s2
    (nt, k1*nt),        mm + s3 ↔ s4
    (a7, k4*a7),              l4 + s1 ↔ s3
    (a7, k4*a7),              l4 + s2 ↔ s4
    (a7, k4*a7),              l4 + f1 ↔ f2
    (a7, k4*a7),              l1 + f1 ↔ f2
    b1,                   s4 → s4 + l2
    b2,                   a4 → a4 + l4
    b3,                   f2 → f2 + l1
    (da,da,da),           (l1, l2, l4) → ∅
    a_dn,                a1 → c1
    kh,                  cp + c1 → c2 + cp
    beta,                c2 →  a1
    m1,              ∅ → l1
    m2,              ∅ → l2
    m3,              ∅ → l4
end k4 k1 k2 a1 d nt a7 b1 b2 b3 da a_dn kh beta m1 m2 m3

p = [0.1, 0.2, 0.2, 5., 5., 500., 500., 5.0, 5.0, 5.0, 5., 5., 5., 5.,  0., 0.05, 0.]
@add_constraints crn begin
  a1 + a3 + a2 + a4 + c1 + c2  = 1
  s1 + s3 + s2 + s4 = 1
  f1 + f2 = 1
end

ss = steady_states(crn,p)
stability(ss,crn,p)

function JE_stability(solution::Vector{Float64}, rn::DiffEqBase.AbstractReactionNetwork, p::Vector{Float64}, t=0.::Float64)
    jac = zeros(length(rn.syms),length(rn.syms))
    rn.jac(jac,solution,p,t)
    return (jac,eigen(jac).values)
end

JE_stability(ss[2], crn, p)[2]
`

The `stability` produce all true for 4 SSS, while explicit calculation for the eigen spectrum gives me a positive real part for the second SSS.

**Comment by isaacsas** [comment]
Please use 

<pre>
```julia
# your code goes in here
```
</pre>

to ensure your code is readable and formatted correct. Thanks!

**Comment by danielchen26** [comment]
Ha, thanks.I was wondering why my code does not show neatly. Here it is:
```julia
# ================ CRN ======================
using DiffEqBiological, LinearAlgebra
crn = @reaction_network begin
(a1, k2a1), l1 + l2 ↔ cp
(d, d), cp + cp ↔ mm
(nt, k1nt), mm + a1 ↔ a2
(nt, k1nt), mm + a3 ↔ a4
(a7, k4a7), l4 + a1 ↔ a3
(a7, k4a7), l4 + a2 ↔ a4
(nt, k1nt), mm + s1 ↔ s2
(nt, k1nt), mm + s3 ↔ s4
(a7, k4a7), l4 + s1 ↔ s3
(a7, k4a7), l4 + s2 ↔ s4
(a7, k4a7), l4 + f1 ↔ f2
(a7, k4*a7), l1 + f1 ↔ f2
b1, s4 → s4 + l2
b2, a4 → a4 + l4
b3, f2 → f2 + l1
(da,da,da), (l1, l2, l4) → ∅
a_dn, a1 → c1
kh, cp + c1 → c2 + cp
beta, c2 → a1
m1, ∅ → l1
m2, ∅ → l2
m3, ∅ → l4
end k4 k1 k2 a1 d nt a7 b1 b2 b3 da a_dn kh beta m1 m2 m3

p = [0.1, 0.2, 0.2, 5., 5., 500., 500., 5.0, 5.0, 5.0, 5., 5., 5., 5., 0., 0.05, 0.]
@add_constraints crn begin
a1 + a3 + a2 + a4 + c1 + c2 = 1
s1 + s3 + s2 + s4 = 1
f1 + f2 = 1
end

ss = steady_states(crn,p)
stability(ss,crn,p)

function JE_stability(solution::Vector{Float64}, rn::DiffEqBase.AbstractReactionNetwork, p::Vector{Float64}, t=0.::Float64)
jac = zeros(length(rn.syms),length(rn.syms))
rn.jac(jac,solution,p,t)
return (jac,eigen(jac).values)
end

JE_stability(ss[2], crn, p)[2]
```

**Comment by isaacsas** [comment]
Great, thanks. Hopefully @TorkelE will have an idea what the issue is.

**Comment by korsbo** [comment]
@TorkelE  is away on a conference for the next two weeks. 

I would imagine that your lack of multiplication operators could cause issues. `k4a7` should be interpreted as a single variable, not the multiplication of two. Does it help if you add `*` wherever you are multiplying things?

**Comment by danielchen26** [comment]
For some reason `*` is not copied correctly. The pasted again. `*` is not the issue. The jocobian spectrum gives me two positive numbers, which means 2 false 2 true. But `stability` return 4 true
```julia
# ================ CRN ======================
using DiffEqBiological, LinearAlgebra

function JE_stability(solution::Vector{Float64}, rn::DiffEqBase.AbstractReactionNetwork, p::Vector{Float64}, t=0.::Float64)
jac = zeros(length(rn.syms),length(rn.syms))
rn.jac(jac,solution,p,t)
return (jac,eigen(jac).values)
end

crn = @reaction_network begin
    (a1, k2*a1), l1 + l2 ↔ cp
    (d, d), cp + cp ↔ mm
    (nt, k1*nt), mm + a1 ↔ a2
    (nt, k1*nt), mm + a3 ↔ a4
    (a7, k4*a7), l4 + a1 ↔ a3
    (a7, k4*a7), l4 + a2 ↔ a4
    (nt, k1*nt), mm + s1 ↔ s2
    (nt, k1*nt), mm + s3 ↔ s4
    (a7, k4*a7), l4 + s1 ↔ s3
    (a7, k4*a7), l4 + s2 ↔ s4
    (a7, k4*a7), l4 + f1 ↔ f2
    (a7, k4*a7), l1 + f1 ↔ f2
    b1, s4 → s4 + l2
    b2, a4 → a4 + l4
    b3, f2 → f2 + l1
    (da,da,da), (l1, l2, l4) → ∅
    a_dn, a1 → c1
    kh, cp + c1 → c2 + cp
    beta, c2 → a1
    m1, ∅ → l1
    m2, ∅ → l2
    m3, ∅ → l4
end k4 k1 k2 a1 d nt a7 b1 b2 b3 da a_dn kh beta m1 m2 m3
@add_constraints crn begin
    a1 + a3 + a2 + a4 + c1 + c2 = 1
    s1 + s3 + s2 + s4 = 1
    f1 + f2 = 1
end

p = [0.1, 0.2, 0.22, 5., 5., 500., 500., 5.0, 5.0, 5.0, 5., 5., 5., 5., 0., 0.05, 0.]
ss = steady_states(crn,p)
stability(ss,crn,p)

@show [round.(real(JE_stability(i, crn, p)[2]),digits = 5) for i in ss]
```

**Comment by TorkelE** [comment]
Hello,

sounds like something fixable. However, it is unlikely that I will be able to have a look at this before I return two weeks from now.

**Comment by TorkelE** [comment]
So I've tried to have a look at this. Two things going on.
- First, when using constraint I do not think one can look at the largest eigenvalue, but have to have the 2nd largest (or third largest if there are 2 constraints, and so on). 
- Secondly, when one account for that, the problem seems to be that the eigenvalues have values at around `0`. This makes it hard to actually figure the stability out. I'm no big expert on this so if anyone have any input on what to do when this happen that would be useful.

**Comment by TorkelE** [comment]
Since the remake, the `stability()` function has been removed.
