### ISSUE TITLE
Obligate Production terms in stochastic differential equations.

### ISSUE THREAD

**Issue by TorkelE** [SciML/DiffEqBiological.jl#21]
I am unsure whenever there is an easy solution to this (but it should be biologically justified).

For a reaction with effect on a specific rate r and stoichiometric change s the deterministic contribution is
s*r
with a stochastic equation this becomes
s*r + s*sqrt(r)*N(0,1)
however, it should be possible under some circumstances for 
s*r < |s*sqrt(r)*N(0,1)|
which would lead to negative production (or if s is negative, positive degradation).

For larger values (when SDEs should be run) I do not think this should be an issue, but I'd still be interested in thinking about if there is some way to prevent this (without major slowdown, which might be required and would make it not worth it).

**Comment by ChrisRackauckas** [comment]
It could just truncate additive noise term when it's below a certain user-chosen value. Technically your noise has to be discrete when the copy number gets really small, so the user can choose a value for what "a few" particles means, at which point we make the contribution deterministic to not go negative. We can soften the transition by smoothing it out a bit. Technically the noise should be larger in that case though, so I'm not sure theory will match here.

**Comment by Gaussia** [comment]
I am having a small list of things to do, at some point I'll sit down and implement them.
