### ISSUE TITLE
Diversify @reaction_network input options

### ISSUE THREAD

**Issue by TorkelE** [SciML/DiffEqBiological.jl#31]
Right now a reaction network can be declared as:
```julia
@reaction_network(name, ex::Expr, p...)
@reaction_network(name, scale_noise, ex::Expr, p...)
@macro reaction_network(ex::Expr)
```
with the last one being a special case, returning an error message that the DSL have been updated.

Two things I have been thinking about:
- In some situations a specific type is not needed
- In #19 I suggested updating to affine noise, like (noise_mult, noise_add)
Now the structure of all the possible inputs: The custom type, the noise, the reaction network, and the parameters are all different. It feels unnecessary to require to input them al. 

While right now the only two correct ways to create a reaction network is:
```julia
rn = @reaction_network rnType begin
    1.0, X --> Y
end
rn = @reaction_network rnType η begin
    1.0, X --> Y
end
```
with
```julia
rn = @reaction_network begin
    1.0, X --> Y
end
```
yielding a deprecating message. The parameters are optional. I think it would be an improvement to make all these kinds of input possible:
```julia
rn = @reaction_network begin
    1.0, X --> Y
end
rn = @reaction_network rnType begin
    1.0, X --> Y
end
rn = @reaction_network rnType (noise_mult,1.0) begin
    1.0, X --> Y
end
rn = @reaction_network (noise_mult,1.0) rnType begin
    1.0, X --> Y
end
rn = @reaction_network (noise_mult,noise_add) begin
    1.0, X --> Y
end
```
(the noise may be declared as a parameter or a constant value)

Again with the possibility of adding parameters at the end. It would be easy to make the program check what input is given and put it in the right box. The biggest issue is if we want to enable the declaration of networks with neither noise or type, in which case we would have to remove the deprecation warning.

**Comment by isaacsas** [comment]
These could be added now as `kwargs` in the corresponding `convert` call in MT, so I’m going to close this issue here.
