### ISSUE TITLE
Feature request: automatic graph generation. 

### ISSUE THREAD

**Issue by korsbo** [SciML/DiffEqBiological.jl#33]
I would often find it useful to visualise a network with an interaction graph. It should be possible to provide a field with sufficient information for such a graph to be automatically generated. 

We could either generate the graph according to some pre-existing graph language ([LightGraphs.jl](https://github.com/JuliaGraphs/LightGraphs.jl)?), or just output some fairly raw data and let that processing be done elsewhere (like the expressions and [Latexify.jl](https://github.com/korsbo/Latexify.jl))

This is a fairly rough idea, and I have not done much research on it, but it would be cool.

**Comment by ChrisRackauckas** [comment]
I think it would be best to integrate with LightGraphs.jl, and then if necessary build some Latexify.jl functions off of LightGraphs.jl since that would be more generally useful anyways. Integrating with LightGraphs.jl would give all of the graph analysis tooling we'd want and more, and sooner or later we'd want it, so it's probably best to just start in that direction.

**Comment by korsbo** [comment]
I think that this idea would be easier to implement here than in ModellingTools.jl, but I don't want to replicate work. Is this something that should be done there rather than here?

**Comment by ChrisRackauckas** [comment]
I honestly don't know. We'll have to see what @AleMorales is up to.

**Comment by korsbo** [comment]
[MetaGraphs.jl](https://github.com/JuliaGraphs/MetaGraphs.jl) (an extension of LightGraphs.jl) looks like it may have some features that we want.

**Comment by isaacsas** [comment]
Shouldn't exporting into the generated reaction_network type the variable `reactions` from the `coordinate` routine of `reaction_network.jl` should provide all the needed info to build network graphs? (It is a `Vector{ReactionStruct}`.) It has the reactant and product stochiometry for each reaction. This info is also needed for mass_action specialized SSAs like I've been working on, so would be very useful for me to have access to through from the `reaction_network`.

**Comment by isaacsas** [comment]
I should add, if this is felt to be a reasonable approach I can submit a PR... I've already made the updates in my local copy...

**Comment by ChrisRackauckas** [comment]
That should be all that's necessary, though having LightGraphs/MetaGraphs.jl support would be nice because it would give functionality like plotting for free. Your code may be a very helpful step to getting there though.

**Comment by isaacsas** [comment]
I agree, adding that support would be great! I only meant that nothing else needed to be directly exposed from the `reaction_network` to enable adding that support. I'll submit the PR -- I haven't done one before so I apologize if I make it more difficult than necessary...

**Comment by ChrisRackauckas** [comment]
No worries! We'll help you through it.

**Comment by isaacsas** [comment]
@korsbo What kind of network did you have in mind? I've been slowly adding network functionality with the new API (like dependency graphs), but am not sure what type of network you were thinking of.

**Comment by ChrisRackauckas** [comment]
done by https://mtk.sciml.ai/dev/systems/DependencyGraphs/ + LightGraphs
