### ISSUE TITLE
Enable creation of problems with AffineNoise

### ISSUE THREAD

**Issue by TorkelE** [SciML/DiffEqBiological.jl#61]
So there exists methods to efficiently solve certain affine noise SDE problems (http://juliadiffeq.org/2018/04/15/StableSDE.html). This is cool (and useful) and should be included in this. Admittedly this depends a little bit of the state of those solver and the Modelling Toolkit (which seems to have started getting some attention again?).

If integrating this into the modelling toolkit, and getting affine noise problems "for free" seems far off we could enable the `@reaction_network` macro to generate the corresponding equations. We could have a flag to the construction like:
```
SDEProblem(model,u0,tspan,p,affine=true)
```
to designate that we want to create this type of problem instead. The multiplicative and additive noise could either be taken as the two last parameters in the `p` vector, or given as a tupple:
```
SDEProblem(model,u0,tspan,p,affine=true,(k,m))
```

**Comment by ChrisRackauckas** [comment]
Now https://github.com/SciML/ModelingToolkit.jl/issues/405
