### ISSUE TITLE
rhs f and Jacobian representation for larger systems

### ISSUE THREAD

**Issue by isaacsas** [SciML/DiffEqBiological.jl#93]
Now that @TorkelE has been kind enough to put in Jacobian support I was thinking a bit about how we might want to handle `f` and the Jacobian for larger systems (where we don't want to make a dense matrix).

It seems like one approach would be the following: let S denote the net stoichiometry matrix and R(u) the vector of rate laws. Then 

du = S * R(u)

so we could simply evaluate R(u) as a vector, and then apply the stoichiometry for each reaction to fill in du. This could be done with a sparse matrix to store S, or some other representation. To make this more automatic I was thinking we could just generate a mutable struct that stores S and the cache vector for R(u), and supplies a functor for evaluating the ODE rhs.

Similarly, for the Jacobian we could store a sparse D[R(u)] and multiply it against S to get D[u].

Does this sound reasonable, or are there other approaches that might be more performant for large systems? The approach above does avoid calculating a rate expression more than once per reaction.

Edit: Or perhaps we should just provide a function that gives the action of the Jacobian on a vector and restrict the underlying linear solvers that can be used.

**Comment by TorkelE** [comment]
I think I understand. Would this yield a big increase in performance (in many cases I imagine the reaction rate is a simple expression of p1*x1*x2, only calculated maybe 4 times. But maybe this is enough for us to get a significant increase using this approach?).

I don't think there is any disadvantage to make sparse matrices? I guess we should convert to those at some point. Do people ever use SDEs for large system? The SDE matrix is large and could probably save a lot of time if it is made sparse.

**Comment by isaacsas** [comment]
For evaluating `f` I'm not sure if this will actually give a performance increase -- it could be using and accessing the cache vector/matrix are more expensive than evaluating the rates multiple times. We'd have to try it out to see. If there are lots of reactions, then `R(u)` would actually be a much larger vector than `du`.

For the Jacobian, using sparse matrices will definitely be necessary for big systems, even if we just directly fill in one sparse `J` (similar to the code you added to fill in a full `J`). I'd expect them to be slower for small systems though. If we initially add use of them through a kwarg (`use_sparsejacobian`?) we could then do some testing to see at what system sizes they start to make sense. At that point we could make an automatic switch in the DSL for large enough system sizes.

**Comment by ChrisRackauckas** [comment]
@isaacsas is spot on here. Optional but the simple DSL should use a heuristic

**Comment by isaacsas** [comment]
Just to update here; BioNetGen can use CVODE_BDF with a (dense) Jacobian evaluation function they generate for a ~1100 species network just fine (solves take about 90s).

In contrast, if I try to call `CVODE_BDF()` with no Jacobian it takes way longer (~300s). If I try to generate the dense Jacobian here with DiffEqBiological, `addodes!` errors out with:
```
ERROR: LoadError: syntax: expression too large
Stacktrace:
 [1] eval at ./boot.jl:328 [inlined]
 [2] eval at /Users/isaacsas/.julia/packages/DiffEqBiological/oca8g/src/DiffEqBiological.jl:3 [inlined]
 [3] #addodes!#33(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol,Symbol},NamedTuple{(:build_jac, :build_symfuncs),Tuple{Bool,Bool}}}, ::Function, ::ParseRxNetwork.testbcrbngbng) at /Users/isaacsas/.julia/packages/DiffEqBiological/oca8g/src/maketype.jl:143
 [4] (::getfield(DiffEqBiological, Symbol("#kw##addodes!")))(::NamedTuple{(:build_jac, :build_symfuncs),Tuple{Bool,Bool}}, ::typeof(addodes!), ::ParseRxNetwork.testbcrbngbng) at ./none:0
 [5] top-level scope at /Users/isaacsas/.julia/packages/TimerOutputs/sc5fl/src/TimerOutput.jl:186
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] include(::String) at ./client.jl:403
 [10] top-level scope at none:0
```

There must be a way to rewrite our Jacobian generation code that can actually compile a function for evaluating large dense Jacobians. For reference, the BioNetGen Jacobian routine is [here](https://github.com/RuleWorld/bionetgen/blob/515b26f460d2c6962e3df48e3cee05824c63147a/bng2/Network3/src/network.cpp#L2766). (It is MIT licensed...)

**Comment by isaacsas** [comment]
I've now tried two alternative `f` implementations. Each goes through all reactions, calculates the rate law, and then for each modified species multiplies the rate law by the appropriate net stoichiometry coefficient and adds it into the corresponding ODE. The version where this is all fully generated works for any network, but is noticeably slower than our current `f`. A compact loop-based version using sparse matrices to represent the stoichiometry, which I only tried for mass action systems, is 25% slower on the BCR network, and that was in a special case where I assumed rate constants were pre-scaled. So my conclusion is our current `f` isn't easy to beat without losing generality (i.e. assuming rates are hardcoded) or perhaps doing some fancy reaction reordering for improved memory efficiency  :) (In fairness, @ChrisRackauckas has basically said this all along, but I wanted to convince myself.) 

One clear optimization I noticed we should make is to multiply out the ODE rate law factorials, explicitly calculate one over them, and then multiply by that in the generated expressions. This would have a drawback though -- the Latexify ODE output would not be as nice.

**Comment by ChrisRackauckas** [comment]
>One clear optimization I noticed we should make is to multiply out the ODE rate law factorials, explicitly calculate one over them, and then multiply by that in the generated expressions. This would have a drawback though -- the Latexify ODE output would not be as nice.

The LLVM common subexpression elimination pass does exactly this to make sure that common subexpressions are only calculated once, so there's no reason to do it manually. Though if we wanted to, we could apply CommonSubexpressions.jl

**Comment by isaacsas** [comment]
Am I misunderstanding this? Or is the optimization happening at a lower level? I'm not that familiar with `code_llvm` but this is showing an `fdiv`:
```julia
f = x -> x / (factorial(10))
 @code_llvm f(4.4)

;  @ REPL[49]:1 within `#107'
define double @"julia_#107_14667"(double) {
top:
; ┌ @ combinatorics.jl:27 within `factorial'
; │┌ @ combinatorics.jl:21 within `factorial_lookup'
    %1 = call i64 @julia_getindex_12956(%jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 4628126928 to %jl_value_t*) to %jl_value_t addrspace(10)*), i64 10)
; └└
; ┌ @ promotion.jl:316 within `/'
; │┌ @ promotion.jl:284 within `promote'
; ││┌ @ promotion.jl:261 within `_promote'
; │││┌ @ number.jl:7 within `convert'
; ││││┌ @ float.jl:60 within `Type'
       %2 = sitofp i64 %1 to double
; │└└└└
; │ @ promotion.jl:316 within `/' @ float.jl:401
   %3 = fdiv double %0, %2
; └
  ret double %3
}
```

**Comment by isaacsas** [comment]
FYI, same output with a `factorial(3)`...

**Comment by isaacsas** [comment]
That the first below doesn't get optimized away surprises me even more:
```
julia> f2 = x -> (1/factorial(3))*x
#13 (generic function with 1 method)

julia> @code_llvm f2(4.4)

;  @ REPL[9]:1 within `#13'
define double @"julia_#13_12336"(double) {
top:
; ┌ @ combinatorics.jl:27 within `factorial'
; │┌ @ combinatorics.jl:21 within `factorial_lookup'
    %1 = call i64 @julia_getindex_12275(%jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 4519742672 to %jl_value_t*) to %jl_value_t addrspace(10)*), i64 3)
; └└
; ┌ @ int.jl:59 within `/'
; │┌ @ float.jl:271 within `float'
; ││┌ @ float.jl:256 within `Type' @ float.jl:60
     %2 = sitofp i64 %1 to double
; │└└
; │ @ int.jl:59 within `/' @ float.jl:401
   %3 = fdiv double 1.000000e+00, %2
; └
; ┌ @ float.jl:399 within `*'
   %4 = fmul double %3, %0
; └
  ret double %4
}

julia> f2 = x -> (1/6)*x
#15 (generic function with 1 method)

julia> @code_llvm f2(4.4)

;  @ REPL[11]:1 within `#15'
define double @"julia_#15_12342"(double) {
top:
; ┌ @ float.jl:399 within `*'
   %1 = fmul double %0, 0x3FC5555555555555
; └
  ret double %1
}
```

**Comment by ChrisRackauckas** [comment]
Wait, what are you looking for this to optimize?

**Comment by isaacsas** [comment]
The division. The current generated code has lots of divisions from factorials within rate laws I thought. If they aren't getting optimized away shouldn't we just explicitly evaluate and invert them to replace with multiplications?

**Comment by ChrisRackauckas** [comment]
Create a function for ff(x) = 1/factorial(n), and then CSE would only evaluate ff(x) once for each input, so it would minimize it. This is probably a micro optimization though.

**Comment by isaacsas** [comment]
@TorkelE In calculating the symbolic Jacobian, why did you convert from the species symbols to internal variables here:

https://github.com/JuliaDiffEq/DiffEqBiological.jl/blob/3d9138ccdea382add1a80082c915ac353fc8c65d/src/reaction_network.jl#L606

but then convert back here:

https://github.com/JuliaDiffEq/DiffEqBiological.jl/blob/3d9138ccdea382add1a80082c915ac353fc8c65d/src/reaction_network.jl#L610

Why not just work with derivatives with respect to the symbols? Was this a scoping issue? (I'm trying to understand the design before putting together sparse Jacobian code...)

**Comment by TorkelE** [comment]
To be honest I am not really sure. I pretty much reused some old code for the jacobian calculation that was lying around, but not used.

My guess is that `SymEngine` needed `SymEngine.Basic` objects to do the derivatives. However, we want our output as expressions and so covert to `SymEngine.Basic` to do the derivative, and then back to `Expr`. 

But from a performance point of view this is likely non-optimal, if this can be done without going around to `SymEngine.Basic` it is probably better (maybe it is as easy as just doing the same on the expressions directly).

**Comment by isaacsas** [comment]
I'm going to play around with two changes here:

1. I think we should be able to avoid the two `recursive_replace` calls that convert to/from internal variables, and just directly take derivatives with respect to the species names. 
2. I think it makes sense here to instead loop over reactions, calculate the rate law derivatives, multiply by the appropriate stoichiometry coefficient, and then append into the expression for the corresponding term in the Jacobian. This shouldn't change the final code we generate (modulo changing the order of terms within each `J[i,j]=` equation), but allows us to calculate derivatives for mass action reactions directly, avoiding the need to use SymEngine for those reactions (and hopefully speeding up the Jacobian generation). Later we should think about using ModelingToolKit for calculating these derivatives (with the current documentation I haven't been able to figure out how to simply take the derivative of an expression with MT, but hopefully the API will expand in the future to enable such things).

**Comment by ChrisRackauckas** [comment]
>Later we should think about using ModelingToolKit for calculating these derivatives (with the current documentation I haven't been able to figure out how to simply take the derivative of an expression with MT, but hopefully the API will expand in the future to enable such things).

```
@derivative D~x
expand_derivatives(D(expr))
```

**Comment by isaacsas** [comment]
Congrats! Where was it accepted to be presented?

Could you or someone working on MT perhaps give me an example of the workflow I would want to use for defining and differentiating rate laws? Basically, I'm not quite groking how to take a Julia expression for a rate law and get it into MT, differentiate it, and then pull out a (simplified) Julia expression that corresponds to the derivative. i.e. something like:

```julia
@parameters k t
@variables DNA(t) MRNA(t) P(t)
ratelawex = :(k*DNA^2/2*P^3/6)
```
How do I generate a MT expression I can differentiate from `ratelawex`, say `R1`? Assuming that can be done I (think I) now have a variable equivalent to:
```julia
R1 = k*DNA^2/factorial(2)*P^3/factor(3)

# derivative
@derivatives D'~DNA
expand_derivatives(D(R1))
```
This gives something like:
```julia
DNA ^ (2 - 1) * 2 * k * inv(2) * P ^ 3 * inv(6)
```
How do I now simplify the constants in the resulting Operation? (I see I can use `convert` to get an `Expr` from it, which is what I ultimately need.)

**Comment by ChrisRackauckas** [comment]
>How do I now simplify the constants in the resulting Operation? (I see I can use convert to get an Expr from it, which is what I ultimately need.)

Hehe, we still need to work on simplification. That's why we got @HarrisonGrodin 👍. Basically it will end up using Rewrite.jl, and common simplification rules then just need to be added there and it will apply a fancy algorithm to do it quickly. My first attempts at simplification were just recursive-based and far too slow to be used in practice, so Rewrite.jl is pretty necessary here.

**Comment by ChrisRackauckas** [comment]
Also, simplifying the syntax of this is listed as https://github.com/JuliaDiffEq/ModelingToolkit.jl/issues/109 .

**Comment by isaacsas** [comment]
Got it. And i guess I can get my Julia `Expr` into MT by just using `eval`, i.e. given I've already defined the parameters and variables:
```julia
ratelawex = :(k*DNA^2/2*P^3/6)
R1 = eval(ratelawex)
```

**Comment by isaacsas** [comment]
Updated TODO list once https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/120 is merged:
- [ ] Update parameter jacobian to specialize mass action reactions
- [ ] creating sub-functions to handle large Jacobian expression lists
- [ ] sparse Jacobian and parameter Jacobian support
- [ ] Jacobian and parameter Jacobian action support

**Comment by ChrisRackauckas** [comment]
Now this is simply a case of https://github.com/SciML/ModelingToolkit.jl/issues/281
